language: python
python: "3.6"
script:
  - make test
deploy:
  provider: pypi
  username: "__token__"
  password: "pypi-AgEIcHlwaS5vcmcCJDZhNjQ4ZDg0LWNiODYtNDQ1OC05ZmZlLTczNWJhMjQ1M2M3NAACRXsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJhd3Mta2luZXNpcy1jb25zdW1lciJdfSwgInZlcnNpb24iOiAxfQAABiBVn6VeG0-8NEaeh7HxKxyBeh5glyvITYrkLnEdxnEU2A"
  on:
    tags: true